=== marekjanec/WebPub/zadanie01.dtd
<!ELEMENT kniznice (kniznica)>
<!ELEMENT kniznica (zanre,uzivatelia,knihovnici,autori)>

<!ELEMENT zanre (zaner+)>

<!ELEMENT zaner (meno, knihy)>
<!ELEMENT meno (#PCDATA)>
<!ELEMENT knihy (kniha+)>

<!ELEMENT kniha (nazov, pocet_stran)>

<!ELEMENT nazov (#PCDATA)>
<!ELEMENT pocet_stran (#PCDATA)>

<!ATTLIST kniha id ID #REQUIRED>
<!ATTLIST kniha autorID IDREF #REQUIRED>

<!ELEMENT uzivatelia (uzivatel*)>
<!ELEMENT uzivatel (meno, datum_narodenia, vypozicka)>

<!ELEMENT datum_narodenia (#PCDATA)>
<!ELEMENT vypozicka (pozicana_kniha*)>
<!ATTLIST uzivatel id ID #REQUIRED>

<!ELEMENT pozicana_kniha EMPTY>
<!ATTLIST pozicana_kniha idKnihy IDREF #REQUIRED>
<!ATTLIST pozicana_kniha vypozicane_do CDATA #REQUIRED>
<!ATTLIST pozicana_kniha stav (vypozicane|vratene|nevratene)>

<!ELEMENT knihovnici (knihovnik+)>

<!ELEMENT knihovnik (meno, datum_narodenia)>

<!ELEMENT autori (autor+)>
<!ELEMENT autor (meno, pocet_knih, datum_narodenia)>
<!ELEMENT pocet_knih (#PCDATA)>
<!ATTLIST autor id ID #REQUIRED>

=== marekjanec/WebPub/zadanie01.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="zadanie02.xsl"?>
<!DOCTYPE kniznice SYSTEM "/zadanie01.dtd">
<kniznice>
    <kniznica nazov="Kniznica Ruzinov" adresa="Ruzinovska 10, Bratislava Ruzinov">
        <zanre>
            <zaner>
                <meno>Kukurica</meno>
                <knihy>
                    <kniha id="k1" autorID="a2">
                        <nazov>Kukuriaca na 1000 spôsobov</nazov>
                        <pocet_stran>1001</pocet_stran>
                        <informacie>Kratky popis pre tuto uzasnu knihu</informacie>
                    </kniha>
                    <kniha id="k2" autorID="a2">
                        <nazov>Kukuričné pole</nazov>
                        <pocet_stran>345</pocet_stran>
                        <informacie>Kratky popis pre tuto uzasnu knihu</informacie>
                    </kniha>
                    <kniha id="k3" autorID="a2">
                        <nazov>Hus útočí na kukuricu</nazov>
                        <pocet_stran>234</pocet_stran>
                        <informacie>Kratky popis pre tuto uzasnu knihu</informacie>
                    </kniha>
                    <kniha id="k4" autorID="a2">
                        <nazov>Peter spadol z kukurice</nazov>
                        <pocet_stran>654</pocet_stran>
                        <informacie>Kratky popis pre tuto uzasnu knihu</informacie>
                    </kniha>
                    <kniha id="k5" autorID="a2">
                        <nazov>Kukurica v tme</nazov>
                        <pocet_stran>263</pocet_stran>
                        <informacie>Kratky popis pre tuto uzasnu knihu</informacie>
                    </kniha>
                    <kniha id="k6" autorID="a1">
                        <nazov>Zmluva s kukuricou</nazov>
                        <pocet_stran>753</pocet_stran>
                        <informacie>
                            <link link_value="www.zmluvaskukuricov.sk"/>
                        </informacie>
                    </kniha>
                    <kniha id="k7" autorID="a1">
                        <nazov>Letna kukurica</nazov>
                        <pocet_stran>142</pocet_stran>
                        <informacie>
                            <link link_value="www.letnakukurica.sk"/>
                        </informacie>
                    </kniha>
                    <kniha id="k8" autorID="a1">
                        <nazov>Lov na kukuricu</nazov>
                        <pocet_stran>234</pocet_stran>
                        <informacie>
                            <link link_value="www.lovnakukuricu.sk"/>
                        </informacie>
                    </kniha>
                    <kniha id="k9" autorID="a1">
                        <nazov>Papezova kukurica</nazov>
                        <pocet_stran>453</pocet_stran>
                        <informacie>
                            <link link_value="www.pk.sk"/>
                        </informacie>
                    </kniha>
                    <kniha id="k10" autorID="a1">
                        <nazov>Cvicime s kukuricou</nazov>
                        <pocet_stran>300</pocet_stran>
                        <informacie>
                            <link link_value="www.cvicimeskukuricov.sk"/>
                        </informacie>
                    </kniha>
                </knihy>
            </zaner>
            <zaner>
                <meno>Mrkva</meno>
                <knihy>
                    <kniha id="k11" autorID="a2">
                        <nazov>Mrkva na 1000 spôsobov</nazov>
                        <pocet_stran>1001</pocet_stran>
                        <informacie>Kratky popis pre tuto uzasnu knihu</informacie>
                    </kniha>
                </knihy>
            </zaner>
            <zaner>
                <meno>Jablka</meno>
                <knihy>
                    <kniha id="k21" autorID="a2">
                        <nazov>Jablka na 1000 spôsobov</nazov>
                        <pocet_stran>1001</pocet_stran>
                        <informacie>Kratky popis pre tuto uzasnu knihu</informacie>
                    </kniha>
                </knihy>
            </zaner>
        </zanre>
        <uzivatelia>
            <uzivatel id="u1">
                <meno>Michal Hodina</meno>
                <datum_narodenia>16.6.2000</datum_narodenia>
                <vypozicka>
                    <pozicana_kniha idKnihy="k9" vypozicane_do="15.3.2021" stav="nevratene"/>
                </vypozicka>
            </uzivatel>
            <uzivatel id="u2">
                <meno>Nadežda Nablhova</meno>
                <datum_narodenia>25.5.1992</datum_narodenia>
                <vypozicka>
                    <pozicana_kniha idKnihy="k2" vypozicane_do="12.4.2021" stav="vratene"/>
                    <pozicana_kniha idKnihy="k6" vypozicane_do="15.4.2021" stav="vypozicane"/>
                </vypozicka>
            </uzivatel>
            <uzivatel id="u3">
                <meno>Vladimir Soletka-Hlacina</meno>
                <datum_narodenia>15.3.1999</datum_narodenia>
                <vypozicka>
                    <pozicana_kniha idKnihy="k1" vypozicane_do="10.3.2021" stav="vypozicane"/>
                </vypozicka>
            </uzivatel>
            <uzivatel id="u4">
                <meno>Adam Prvy</meno>
                <datum_narodenia>15.3.1999</datum_narodenia>
                <vypozicka/>
            </uzivatel>
        </uzivatelia>
        <knihovnici>
            <knihovnik>
                <meno>Lucia Falbova</meno>
                <datum_narodenia>24.12.1981</datum_narodenia>
            </knihovnik>
        </knihovnici>
        <autori>
            <autor id="a1">
                <meno>John Corn</meno>
                <pocet_knih>5</pocet_knih>
                <datum_narodenia>18.3.1970</datum_narodenia>
            </autor>
            <autor id="a2">
                <meno>Peter Kukurica</meno>
                <pocet_knih>8</pocet_knih>
                <datum_narodenia>6.6.1966</datum_narodenia>
            </autor>
        </autori>
    </kniznica>
</kniznice>
